### ISSUE TITLE
How to get it working with Keystone.js?

### ISSUE THREAD

**Issue by art1c0** [buunguyen/mongoose-deep-populate#1]
First of all thanks for a great plugin!
I'm trying to use your plugin within Keystone.js application and cannot get it working.
Keystone uses own mechanism of Lists although it's based on mongoose.
I tried to do something like that:

var list = keystone.list('Thing');
list.schema.plugin(deepPopulate);
list.deepPopulate  ---- method is undefined
list.model.deepPopulate  ---- method is undefined

If you can give any help on how to get this working it would be really great and will expand usage of your plugin as well :)

**Comment by askdesigners** [comment]
And is it correct that querying should look like:
`Day.model.find().deepPopulate('userdays userdays.user').exec(function....`
?

Doing this throws an error " TypeError: Object #<Query> has no method 'deepPopulate' " Am I missing something?

**Comment by buunguyen** [comment]
Is this for Keystone.js? The gist is that this plugin extends the following Mongoose objects: query, model and model instance. I'm not sure how Keystone.js integrates with Mongoose, just make sure you invoke `deepPopulate` on the right object.

**Comment by buunguyen** [comment]
@articobandurini just so you know, the latest version of the plugin supports selecting specific fields for the output.

**Comment by egaba88** [comment]
+1 I am also curious to know if anyones got this to work with Keystone.js?

**Comment by VykintasZaboras** [comment]
I'm doing:
```
Post.paginate({
	page: req.query.page || 1,
	perPage: 50,
	maxPages: 10
}).populate('comments','author content date')
.deepPopulate('author.name')
```

and i included the plugin like so:
```
var deepPopulate = require('mongoose-deep-populate');
Post.schema.plugin(deepPopulate);
Post.register();
```

But i still get the error:
```
TypeError: undefined is not a function
```

Anyone got it working with keystone?

**Comment by buunguyen** [comment]
See https://github.com/buunguyen/mongoose-deep-populate/issues/18#issuecomment-110934841 (kudos to @AndrewFinlay). Basically Keystone and this plugin uses different instances of Mongoose. The fix is explicitly adding Mongoose as a dependency in package.json.
