### ISSUE TITLE
Unclear Docs

### ISSUE THREAD

**Issue by sabrehagen** [buunguyen/mongoose-deep-populate#11]
Hi,

This library is great, but it was missing one key example of how to use the plugin that had me searching for hours and almost gave up on using it. I couldn't work out how to populate multiple paths, and select different fields for each. If you could include something like this in the docs, it could help others greatly in future!

    app.models.project
    .findOne({ _id : req.params.id })
    .deepPopulate('team.member comments.owner', {
        populate : {
            'team.member' : {
                select : 'profile.firstname profile.lastname profile.picture profile.username',
            },
            'comments.owner' : {
                select : 'profile.firstname profile.lastname profile.picture profile.username profile.blurb'
            }

        }
    })
    .exec(function(err, project) {
    });

**Comment by buunguyen** [comment]
The readme already includes [such example](https://github.com/buunguyen/mongoose-deep-populate#specify-options). Not only does it features the exact usage you mentioned, it also follows the same schemas as the rest of the examples. Not sure why you think it's unclear. 

```javascript
PostSchema.plugin(deepPopulate, {
  populate: {
    'comments.user': {
      select: 'name',
      options: {
        limit: 5
      }
    },
    'approved.user': {
      select: 'name'
    }
  }
});
```

**Comment by sabrehagen** [comment]
There are two distinct differences between your code and my code. Mine is being used inline in the query chain, and mine requires you to specify the paths as the first parameter to deep populate. The only time you demonstrate the plugin on a query, you change the find option between find(), findOne(), and findById(), thus demonstrating the flexibility of mongoose perfectly well, but not demonstrating the flexibility of deep populate in the query context.

Not sure why you don't think it's unclear.

**Comment by buunguyen** [comment]
> The only time you demonstrate the plugin on a query

Well, the readme includes yet another example, that matches your use case:
```
Post.find({}).deepPopulate(paths, {
  whitelist: [],
  populate: {},
  rewrite: {}
}).exec(cb)
```
I feel the pain of having to spent time working out your specific use case. But in this case, I think the documentation should answer all your questions if you read it carefully.

**Comment by sabrehagen** [comment]
And at what point in your sample code do you initialize paths?
