### ISSUE TITLE
Select parent populate fields

### ISSUE THREAD

**Issue by sabrehagen** [buunguyen/mongoose-deep-populate#13]
I have the following data structures:

```javascript
var userSchema = Schema({
    projects         : [{ type : ObjectId, ref     : 'Project' }],
});

var projectSchema = Schema({
    name             :  { type : String,     default : ''             },
    projectDetails   :  { type : String,     default : ''             },
    team             : [{
        _id          : {  type : ObjectId,   ref     : 'User'         },
        role         : {  type : String,     default : 'Contributor'  },
        owner        : {  type : Boolean,    default : false          }
    }],
});
```
I want to use deepPopulate on the userSchema to populate the projects, and each project's team._id's. Currently I can only work out how to apply a select to the fields of the project.team populate, not the project populate. I don't want to select the projectDetails property of the project as this is a large amout of data. How, when using deepPopulate, do I specify which fields to select in the project populate, as well as in the project team populate?

**Comment by buunguyen** [comment]
Something like this:

```javascript
UserSchema.plugin(deepPopulate, {
  populate: {
    projects: {
      select: '-projectDetails'    
    }
  }
});
```

You can also specify the option on a per-call basis. Please refer to the README.

**Comment by sabrehagen** [comment]
Your answer doesn't populate the team._id field.

**Comment by buunguyen** [comment]
If you could add a failed test case to https://github.com/buunguyen/mongoose-deep-populate/blob/master/test/plugin.js, I can look at it.
