### ISSUE TITLE
TypeError Cannot read property 'lean' of undefined

### ISSUE THREAD

**Issue by EddyNll** [buunguyen/mongoose-deep-populate#14]
I'm having trouble with the following issue:
TypeError: Cannot read property 'lean' of undefined
plugin.js line 36

**Comment by buunguyen** [comment]
Which version of Mongoose? Can you post your usage? Even better, can you post a failed test?

**Comment by buunguyen** [comment]
Closing now due to inactivity. If you can provide info to reproduce the issue, I'll reopen.

**Comment by nikopolidi** [comment]
Cannot read property 'lean' of undefined
"mongoose": "~3.6.20",
"mongoose-deep-populate": "^1.1.0"

coffeescript

Product model:
...
category: 
  type: String
  ref: 'category'
...
CategoryModel:
_id: String
...

Error on

Product.find({})
.skip(0)
.sort(
  date_created: -1
)
.deepPopulate("product product.category")
.exec cb

**Comment by buunguyen** [comment]
Can you add a failed test?

**Comment by nikopolidi** [comment]
I showed u model and query that is what was failed

2015-06-17 21:19 GMT+03:00 Buu Nguyen <notifications@github.com>:

**Comment by buunguyen** [comment]
Can you try with at least Mongoose 3.8?
