### ISSUE TITLE
 Support for hierarchy (recursive population)

### ISSUE THREAD

**Issue by jberzins** [buunguyen/mongoose-deep-populate#15]
Hi,

Is it possible to request deepPopulate of children and children children until whole tree is loaded?

Thanks

**Comment by buunguyen** [comment]
Sorry, it's not possible right now. Pull request is welcome though.

**Comment by quangbuule** [comment]
This should cause infinite loop, I think.

**Comment by pieterjandesmedt** [comment]
It could cause an infinite loop, but you could also supply a cut-off depth...

**Comment by buunguyen** [comment]
Closing this right now. Sort of an edge case, which can be handled in user-land. If there's a PR that is generic enough, I'll gladly accept.
