### ISSUE TITLE
Custom name for the `deepPopulate` method

### ISSUE THREAD

**Issue by irobert91** [buunguyen/mongoose-deep-populate#17]
Hello

I was wondering if it would be a nice/helpful feature to be able to name the methods attached to the models/queries/documents something else than `deepPopulate`.

I think that this would be useful when you want to have 2 or more different sets of options for `deepPopulate`.

For example:
```js
PostSchema.plugin(deepPopulate, {
  whitelist: ['comments.user', 'comments.user.posts']
});
```
When using this internally, I need the posts of the comments' user, but when I am exposing this through an api, I only want `comments.user` to be populatable for security or any other reasons.
What I need to do right now:
```js
// in the route handler, override the options
var fieldsToPopulate = req.query.populate;
Post.find().deepPopulate(fieldsToPopulate, {
  whitelist: ['comments.user']
}).exec(...);
```
This is just an example and it could apply to any other options.

Instead, I believe that it would be a lot cleaner if this could be done:
```js
// if no name is specified, it will default to deepPopulate
PostSchema.plugin(deepPopulate, {
  whitelist: ['comments.user', 'comments.user.posts']
});

// with custom name
PostSchema.plugin(deepPopulate, {
  pluginName: 'publicPopulate',
  whitelist: ['comments.user']
});

// so later you would be able to call it like this:
Post.find().publicPopulate(fieldsToPopulate).exec(...);
```

Of course, the example I gave with `pluginName` is just a suggestion.
This way, you would not need to override the options every time.

**Comment by buunguyen** [comment]
I think something like this should in user-land. For example, something like this would work:
```js
Query.prototype.publicPopulate = function (fields) {
  return this.deepPopulate(fields, {whitelist: ['comments.user']});
}
...
Post.find().publicPopulate(fields).exec()
```
