### ISSUE TITLE
Populate limit option on deep collection

### ISSUE THREAD

**Issue by mnort9** [buunguyen/mongoose-deep-populate#19]
The populate limit option doesn't seem to apply to deep collections as expected (or at least what I expect it to).

For example... 

`user.deepPopulate('items.subitems', { populate: { 'items.subitems': { limit: 3 }}}, ...` 

This returns only 3 total populated subitems, rather than 3 populated subitems per item. If there were 4 items, I thought this would return 12 total populate subitems, 3 from each.

Is this the expected functionality of the limit option?

It wouldn't be a significant issue for me if I had to just set the limit to 12, but the problem is the limit is applied to the first item's subitems, so it returns 12 subitems from only the first item.

**Comment by buunguyen** [comment]
The options look wrong. Try this:

```js
user.deepPopulate('items.subitems', { populate: { 'items.subitems': { options: {limit: 3} }}}}, ...
```

Underneath, the plugin just invokes [Mongoose#populate](http://mongoosejs.com/docs/api.html#model_Model.populate) with these options. So the exact behavior is totally up to Mongoose.

**Comment by mnort9** [comment]
Sorry, that's what I had in my code. I just forgot the options key in the example I included. I guess mongoose is applying the limit to the entire query...

**Comment by buunguyen** [comment]
Might be related to this bug https://github.com/Automattic/mongoose/issues/1490. Probably try to upgrade Mongoose?

**Comment by mnort9** [comment]
Looks related, but I tried upgrading mongoose to 3.8.20 & 3.8.29 with no luck.

**Comment by buunguyen** [comment]
@mnort9 does seem like a bug to me because the behavior you described isn't intuitive. You might want create an example using `populate()` directly and post an issue in mongoose.
