### ISSUE TITLE
The latest update breaks it for mongoose 4+

### ISSUE THREAD

**Issue by ashoksahoo** [buunguyen/mongoose-deep-populate#24]

**Comment by buunguyen** [comment]
Is there a specific version? It does pass the test locally and on Travis with Mongoose 4.

**Comment by TrejGun** [comment]
same for me

**Comment by ashoksahoo** [comment]
It has breaking changes from 1.0

**Comment by buunguyen** [comment]
Oh right, I should have guessed. The breaking change is the reason why I bumped to 2.0 per semantic versioning.
