### ISSUE TITLE
Query find in deep population

### ISSUE THREAD

**Issue by Renouveaux** [buunguyen/mongoose-deep-populate#3]
Hi, 
I'm searching the way to make à usual find in a query and only return the result corresponding, where the searching kay value is on a deepPopulation.
For exemple, I Have a user table, in there a propertie table and in the propertie a state table.
I wanna sort only the list of users who have the name properties equal to "searchKey".
I have make a query Like this, but nothing work.
Users.find({}, function(err, data) {
  Users.deepPopulate(data, 'propertie.state',{
      populate: {
           'propertie.state' : {
                   match: {'name': searchKey}
            }
       }
    }, function(err, _result) {
            console.log(_result);
    });
});

Thanks for your reply.

**Comment by infinito84** [comment]
Look this solution, I made that engineProperties to have a null value instead manufacturers, and after i use Array.filter

```javascript
Engine.find({})
	.deepPopulate('engineProperties.manufacturers', {
		populate: {
			engineProperties : {
				match : {
					manufacturers : new ObjectId('547a38f813411dc14e737b97'),
				}
			}
		}
	})
	.exec(function (error, data) {
		data = data.filter(function(engine){
			return engine.engineProperties;
		});
		console.log(data);
	});
```
Output
```javascript
[ { 
	_id: 5499f57afdedd69d46edd869,
	serial: '4561506',
	inventory: '786156',
	label: '12',
	engineProperties: 
	{ 
		_id: 547a39bb13411d1f4b737b96,
		model: 'Modena',
		description: 'Une description à la con',
		manufacturers: 
		{ 
			_id: 547a38f813411dc14e737b97,
			name: 'Diffusion Technique Française',
			address: '19 Rue de la Presse',
			postcode: '42000',
			city: 'Saint-Etienne',
			phone: '+3345648465',
			fax: '+3345656458',
			__v: 0,
			email: [Object] 
		},
		__v: 0 
	},
	__v: 0 
} ]
```
