### ISSUE TITLE
Ambiguity between "paths" argument and "populate" options key

### ISSUE THREAD

**Issue by hstonge** [buunguyen/mongoose-deep-populate#31]
Hi!

Your documentation specifies that you can [override the options per-query](https://github.com/buunguyen/mongoose-deep-populate#overriding-options); what seems confusing is that although you can specify a **populate** key in the options object using the same standard Mongoose populate() syntax, you must also pass as parameter the **paths** list.

Am I missing something, or there seems to be two parameters cancelling each other out ?

Thanks in advance for your help.

**Comment by buunguyen** [comment]
The `populate` key is for settings only. You always have to specify paths to deep-populate.

**Comment by hstonge** [comment]
Hi Buu,

Then when using the following query:
```
Post.find().deepPopulate('comments.user').exec(function (err, post) { ... });
```
how can I specify which field I want to be selected/excluded from the `comments.user` sub-field ?

**Comment by buunguyen** [comment]
It will be something like 

```js
Post.find().deepPopulate('comments.user', {
   populate: {
     'comments.user': {select: 'name'}
   }
})
```

It's in the README https://github.com/buunguyen/mongoose-deep-populate#specify-options.

**Comment by hstonge** [comment]
Oh, right!

Haha, guess I was confused between the example and the "corresponding Mongoose populate options".

Next time, I'll take more time to RTFM.

Thanks !
