### ISSUE TITLE
deepPopulate is not a function {Help}

### ISSUE THREAD

**Issue by lakinoheat** [buunguyen/mongoose-deep-populate#35]
Getting the following error:
TypeError: Role.find(...).deepPopulate is not a function

Here is the used usage:
var mongoose = require("mongoose");
var Schema = mongoose.Schema;
var deepPopulate = require('mongoose-deep-populate')(mongoose);
var schema = {

};
var roleSchema = new Schema(schema);
roleSchema.plugin(deepPopulate);
module.exports = mongoose.model('Role', roleSchema);

code:
Role.find({}).deepPopulate('permissions').populate('permissions.model').exec(console.log);

NB: i am using this with sails-permissions library

**Comment by lakinoheat** [comment]
Someone please help me with the error. Am bit new to this

**Comment by buunguyen** [comment]
I can't see anything wrong with your usage. Maybe post a failed unit test or working (failed) code?
