### ISSUE TITLE
Can't get this simple populate to work in Mongoose 4.4.4

### ISSUE THREAD

**Issue by bitflower** [buunguyen/mongoose-deep-populate#40]
I have the exact same scenario as decribed in this post:
http://stackoverflow.com/questions/13077609/mongoose-populate-embedded/27409526#27409526

However I can't get the properties on the second level to populate. These are:
- head.user
- trunk.user
- legs.user

I want to populated with the virtual property "profile" of the User.

These are my schemas:
var deepPopulate = require('mongoose-deep-populate')(mongoose);

var PersonSchema = new mongoose.Schema({
    name: String,
    head: {
        user: {
            type: Schema.Types.ObjectId,
            ref: 'User'
        }
    },
    trunk: {
        user: {
            type: Schema.Types.ObjectId,
            ref: 'User'
        }
    },
    legs: {
        user: {
            type: Schema.Types.ObjectId,
            ref: 'User'
        }
    }
});

// PersonSchema.plugin(deepPopulate);
PersonSchema.plugin(deepPopulate, {
    populate: {
        'head.user': {
            select: 'profile'
        }
    }
});

// User

var UserSchema = new Schema({
    name: {
        type: String
    },
    email: {
        type: String,
        lowercase: true
    },
    role: {
        type: String,
        default: 'user'
    },
    password: {
        type: String
    },
    provider: {
        type: String
    }
});

// Public profile information
UserSchema
    .virtual('profile')
    .get(function() {
        return {
            '_id': this._id, // Wieder entfernen!
            'name': this.name,
            'role': this.role
        };
    });

Gives me this (No population at all):
{  
   "_id":2,
   "name":"New person",
   "__v":0,
   "legs":{  
   },
   "trunk":{  
      "user":"56c784c5379866ed19e8709d"
   },
   "head":{  
      "user":"56cdf69e01e6db5f2d6bf0a2"
   }
}

I tried to do it in the controller then with this:
Person
    .deepPopulate(entity, 'head.user', function(err, _entity) {
        res.status(statusCode).json(_entity);
    });

This works - however I get the whole User info including password etc.

My questions:
- How is the plugin used properly? Just setting it on the model should be enough?
- Did I use the "select" option correctly? If not how would that look like if used correctly?
- Bug or me doing the wrong things???

Thanks.

**Comment by buunguyen** [comment]
You should format your code. The usage instructions are already in the README. Feel free to submit a PR if anything's unclear.
