### ISSUE TITLE
Return Promise after population of an instance

### ISSUE THREAD

**Issue by RemiAWE** [buunguyen/mongoose-deep-populate#42]
Hi,

First, thank you for your plugin, it is very useful !

I'm actualy using the Mongoose method `Document.populate().execPopulate()` to get a Promise after the population of an instance of my model and I was wondering if there is a way to have a similar workflow with your Plugin.

Have you got a sort of `Document.deepPopulate().execPopulate()` to get a Promise after the population of a instance of a model ?

**Comment by buunguyen** [comment]
Use exec().

**Comment by RemiAWE** [comment]
I tried but `exec()` only works with a Query, not an instance of a Model.

With the `post` model in the examples provided in the documentation, my problem is this:
```JavaScript
post.deepPopulate('comments.user').exec().then(populatedPost => res.json(populatedPost));
// => TypeError: Cannot read property 'exec' of undefined

post.deepPopulate('comments.user').execPopulate().then(populatedPost => res.json(populatedPost));
// => TypeError: Cannot read property 'execPopulate' of undefined
```

**Comment by buunguyen** [comment]
Done. Just published v3. Let me know if it meets your need.

**Comment by RemiAWE** [comment]
It works perfectly :ok_hand:
Thank you very much for your great work
