### ISSUE TITLE
Question - how safe is deep-populate to use with unchecked input?

### ISSUE THREAD

**Issue by hasufell** [buunguyen/mongoose-deep-populate#43]
I am considering to write a REST API that by default just maps the database to the json object, e.g.
```
/products/<product-id>
```
Since there are a lot of object references it makes sense in some cases to allow deep population based on parameters, e.g.
```
/products/<product-id>?details=price,catalogue.store,catalogue.store.leadingMedia
```
where this would end up somewhat like:
```js
foo.deepPopulate(['price', 'catalogue.store', 'catalogue.store.leadingMedia']);
```

Can this lead to stuff like sql injection or is deepPopulate safe in that regard?

**Comment by buunguyen** [comment]
You should [whitelist](https://github.com/buunguyen/mongoose-deep-populate#specify-options) the fields. So it should be safe.
