### ISSUE TITLE
[Suggest] Add keystone specific instructions for usage

### ISSUE THREAD

**Issue by r3wt** [buunguyen/mongoose-deep-populate#45]
1. place the following line immediately after `keystone.init(...);` and before `keystone.import(...)`:
```js
keystone.set('deepPopulate',require('mongoose-deep-populate')(keystone.mongoose));
````

2. to add the plugin to a model use the following code in your model files`
```js
var deepPopulate = keystone.get('deepPopulate');
Model.schema.plugin(deepPopulate);
```

This is the most correct way to do it, as you don't end up needlessly setting up the plugin for each model. instead, you instantiate it once in main and then you can retrieve it from any file. 

Regards

**Comment by buunguyen** [comment]
The plugin initialization does check if it already patch `Query` to avoid unnecessary work. The overhead of `require('mongoose-deep-populate')(mongoose)` is neglectable.

**Comment by r3wt** [comment]
*negligible

**Comment by buunguyen** [comment]
lol, thanks.
