### ISSUE TITLE
Recursive Populate?

### ISSUE THREAD

**Issue by brownish** [buunguyen/mongoose-deep-populate#5]
I'm trying to build a hierarchical taxonomy schema using deepPopulate but I'm not sure if what I'm trying to do is possible (I have been teaching myself javascript so bear with me). I'd like to be able to recursively populate all children objects to an unknown depth. I'm also using [Mongoose-Relationship](https://github.com/sabymike/mongoose-relationship) to push child IDs into the parent's [children] array.

I've got a schema like this:
```
var mongoose = require('mongoose'),
    Schema = mongoose.Schema,
    relationship = require("mongoose-relationship"),
    deepPopulate = require('mongoose-deep-populate');

var TaxonomySchema = new Schema({
  parent: {type: Schema.Types.ObjectId, ref: 'Taxonomy', childPath: "children"},
  children: [{ type: Schema.Types.ObjectId, ref: 'Taxonomy'}],
  name: String,
  description: String
});

TaxonomySchema.plugin(deepPopulate);
TaxonomySchema.plugin(relationship, {relationshipPathName: 'parent'});

module.exports = mongoose.model('Taxonomy', TaxonomySchema);
```

I've been using deepPopulate in my api controller like so:

```
var Taxonomy = require('./taxonomy.model');

var outputArray = [];
var outputOptions = {};

function dpop (i, callback) {
  // run subpop i.num times, building an array of name, name.name,
    // name.name.name etc. and push them into outputArray.
    //Also builds outputOptions to pass to deepPopulate but doesn't work
  var num = i.num;
  var name = i.name;
  function subpop (a, cb) {
    if (a.num < num) {
      var subName = a.name + '.' + a.name;
      var inputOptions = {subName: {select: "name children"}};
      var newNum = a.num +1;
      var newName = a.name + '.' + name;
      outputArray.push(newName);
      outputOptions[subName] = inputOptions;
      subpop({num: newNum, name: newName}, function () {
        console.log(outputArray, outputOptions);
        callback();
      });
    }
  }
  subpop({num: 0, name: name}, function() {
    console.log({values: outputArray, opt: outputOptions});
  });
}

dpop({num: 10, name: 'children'});


// Get list of taxonomys
exports.index = function(req, res) {
  Taxonomy.find({parent: null}).deepPopulate(outputArray, outputOptions).sort('parent').exec(function (err, taxonomys) {
    if(err) { return handleError(res, err); }
    return res.json(200, taxonomys);
  });
};
```

I am using the function `dpop` to generate an array like so: `["children", "children.children", "children.children.children"]` and passing it as the first argument to deepPopulate. I'm certain this is a terribly inefficient solution to this problem but it seems to work but is not recursive.

Is recursively populating children possible?

Thanks!

**Comment by buunguyen** [comment]
The plugin doesn't do recursive population right now. It should be possible to implement by tackling these two problems:

* Knowing when to stop. Probably when references are null, empty or fully populated.
* Dealing with circular references. Probably by maintaining in memory already populated documents and fill them into the references before running the next population iteration.

Most changes can probably be enclosed inside the [`populate`](https://github.com/buunguyen/mongoose-deep-populate/blob/master/lib%2Fplugin.js#L135) function. If you can take a stab at it, I'll gladly accept a pull request.

BTW, regarding your current usage, you can just pass `'children.children.children'` instead of `['children', 'children.children', 'children.children.children']`.

**Comment by brownish** [comment]
Great to know that I can just use `'children.children.children'`. That should make it much easier for the time being.

I am currently looking into using https://github.com/angular-ui-tree/angular-ui-tree for tree manipulation with socket.io and it would be great to be able to utilize deepPopulate. I'm going to see if I can get the basics of that figured out before trying anything more complex.

I'll take a look at the code and see if I can figure something out.

**Comment by buunguyen** [comment]
I'm closing this for now as I probably don't build it myself, seems too much work for a rare use case that can be worked around at the application level. However, if anyone's submitting a PR, I'll gladly consider merging.
