### ISSUE TITLE
deepPopulate function not available

### ISSUE THREAD

**Issue by kristianmandrup** [buunguyen/mongoose-deep-populate#51]
Trying to follow your example, `deepPopulate` is not an available function.

```
  ---
    name: AssertionError
    message: Rejected promise returned by test
    values:
      'Rejection reason:': '[TypeError: Env.findById(...).deepPopulate is not a function]'
    at: 'model._callee$ (packages/red-storage/mongodb/schemas/Project.js:35:10)'
```

Trying to use it here

```js
      return await Env.findById(id)
        .deepPopulate('branch.commits')
        .where('type ').in(types)
    })
```

Works without deepPopulate, but then doesn't populate with nested branch/commits (obviously!)

```js
      return await Env.findById(id)
        .where('type ').in(types)
    })
```

This is my setup

Tried to register locally on `Project` schema

`Project.plugin(deepPopulate)`

Trying to register it globally via `mongoose.plugin`. Is this possible?

```js
var models = require('mongoose-models')
let mongoose = require('mongoose')
mongoose.Promise = global.Promise;

// Register plugins
const deepPopulate = require('mongoose-deep-populate')(mongoose)
const findOrCreate = require('mongoose-findorcreate')

mongoose.plugin(deepPopulate)
mongoose.plugin(findOrCreate)


let methods = {
  envType: async function (types, cb) {
    if (typeof types === 'string') {
      types = [types]
    }
    let envIds = this.environments
    let Env = this.model('Env')
    let envs = envIds.map(async(id) => {
      return await Env.findById(id)
        .deepPopulate('branch.commits')
        .where('type ').in(types)
    })
    return Promise.all(envs)
  }
}

let schema = {
  name,
  description,
  type: String,
  owner: ref('User'),
  environments: refList('Env')
}


models.create('Project', {
  schema,
  methods,
  query: {
    byName: function (name) {
      return this.find({
        name: name
      });
    }
  }
});
```

**Comment by buunguyen** [comment]
This plugin adds the method to `Query` object. Check to make sure mongoose-models returns `Query` somehow.

**Comment by kristianmandrup** [comment]
Aha! then I might need to hack mongoose-models some extra ;) 

But it does create a normal schema

[see here](https://github.com/kristianmandrup/mongoose-models/blob/master/lib/index.js#L211)

And I have since hacked it to do `props.schema.plugin(yourPluginHere)` when it find a `plugins` entry (Object or Array)

[mongoose-models plugins registration](https://github.com/kristianmandrup/mongoose-models/blob/master/lib/index.js#L251)

Thanks anyways
