### ISSUE TITLE
mongoose 5 - fix not working correctly

### ISSUE THREAD

**Issue by simllll** [buunguyen/mongoose-deep-populate#55]
@buunguyen I tried latest version with the new mongoose 5 fix, unfortunately the rewritten fix does not work in my setup. I guess because I'm using the bluebird library.

```
const Promise = require('bluebird'); // bluebird
mongoose.Promise = Promise;

```

Therefore 
`if (mongoose.Promise === Promise) { `is not true in my case. Anyways, I have seen there is a mongoose.version variable available.

I'll create a PR - please review. 

thanks
Simon

**Comment by yamifr07** [comment]
Not working as expected: If I replace "mongoose.Promise === Promise" by true, the plugin works perfect but using the last uploaded code, this conditional returns false so issue still happening.

**Comment by simllll** [comment]
@yamifr07 indeed, this is the same issue I had. I opened already a PR that fixes it.

**Comment by buunguyen** [comment]
Please try 3.1.1. Thanks for suggesting using `version`. Commit: https://github.com/buunguyen/mongoose-deep-populate/commit/8c5ae6df653d1b385a1434189ab7f9e0578c67c9

**Comment by yamifr07** [comment]
@buunguyen version 3.1.1 not found on npm
