### ISSUE TITLE
Mongoose lean() option ignored

### ISSUE THREAD

**Issue by rshov** [buunguyen/mongoose-deep-populate#7]
It seems that when using lean() with deepPopulate() mongoose does not return a pure JSON object as expected. Instead it looks like a mongoose document with all the getters, setters & virtuals, etc. 

Using the example from the documentation, I would be doing something l like this:
Post.findById(postId).deepPopulate('comments.user').lean().exec(function (err, post) {
  // expect a JSON object to be returned rather than a mongoose document
});

Am I doing something wrong or is this a known issue? Thanks.

**Comment by latitudehopper** [comment]
I think I have the same issue. Posted here asking for help.
https://groups.google.com/forum/#!searchin/mongoose-orm/json$20array$20result/mongoose-orm/QCLR9mdfWz4/gOizImZoU8AJ

**Comment by buunguyen** [comment]
@rshov `lean()` does work for me. Please post a failed test case.

@latitudehopper the code you posted doesn't use this plugin at all. Are you sure you use the `deepPopulate` method somewhere?

**Comment by latitudehopper** [comment]
My apologies. I came here through a hasty Google search. You are right, that is not relevant.

**Comment by buunguyen** [comment]
@rshov I've just added a [test case](https://github.com/buunguyen/mongoose-deep-populate/commit/81ccca66ce158bbc062e586110d48796db153b81#diff-7443c2387c35f2528f8cb9fef5cc6495R103) to show that `lean()` works. I'm closing this now, will reopen if you can show a failed test case.

**Comment by rshov** [comment]
@buunguyen You're right, I see it working in the test case. Must have been a problem in my code. I will try to investigate to make sure. Thanks very much for looking into this. You have a great plugin, very useful!

**Comment by PanJ** [comment]
Just came across the same issue. The object is lean except the populated one. Trying to reproduce in test.

**Comment by buunguyen** [comment]
Yeah, I'm working on it, reported in https://github.com/buunguyen/mongoose-deep-populate/issues/8
