### ISSUE TITLE
deepPopulate with lean() only makes the top level object a normal js object

### ISSUE THREAD

**Issue by jpatel71** [buunguyen/mongoose-deep-populate#8]
from what I can tell if I use the deep populate method with lean() the parent doc is returned as a JS object, but all the populated fields returned are still mongoose objects

**Comment by buunguyen** [comment]
I haven't checked, but what is the behavior of the built-in Mongoose `populate` method? I want to keep the semantic the same. I'll probably check this later myself, but if you already know that, love to hear.

**Comment by buunguyen** [comment]
Just an update: I have verified the behavior of Mongoose and `lean` does affect populated objects. I'm going to mimic the behavior in this plugin.
